on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
  release:
    types: [published]
  
name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render
        if: github.event_name == 'pull_request'
        uses: quarto-dev/quarto-actions/render@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Preview
        if: github.event_name == 'pull_request'
        run: |
          QUARTO_PUBLISH_URL="https://ucd-serg.github.io/${{ github.repository }}-preview-${{ github.event.number }}"
          quarto publish gh-pages --server $QUARTO_PUBLISH_URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render and Publish
        if: github.event_name != 'pull_request'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
